networks:
  my_network:

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    platform: linux/amd64
    ports:
      - "9090:9090"
    networks:
      - my_network
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  fluentd:
    image: custom-fluentd
    container_name: fluentd
    platform: linux/amd64
    ports:
      - "24224:24224"
      - "24231:24231"
    networks:
      - my_network
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/logs

  grafana:
    image: grafana/grafana
    container_name: grafana
    platform: linux/amd64
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - fluentd
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
