version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install pytest
      - run:
          name: Create and Run Tests
          command: |
            echo "def test_hello_circleci(): assert True" > test_hello_circleci.py
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
