version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9  # Use the official Python 3.9 Docker image
    steps:
      - checkout  # Checks out your repository
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install pytest  # Install pytest for testing
      - run:
          name: Run Tests
          command: |
            echo "def test_hello_circleci(): assert True" > test_hello_circleci.py  # Example test
            pytest  # Run pytest to execute the tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build  # Execute the 'build' job in the workflow
