version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9  # Use the official Python 3.9 Docker image
    steps:
      - checkout  # Check out the repository
      - run:
          name: Set up Python environment
          command: |
            python -m pip install --upgrade pip  # Upgrade pip
            pip install -r requirements.txt  # Install all dependencies listed in requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest --maxfail=1 --disable-warnings  # Run pytest with basic options to handle errors gracefully

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
